name: Run Code at 4 PM Monday-Friday

on:
  schedule:
    # Runs at 4 PM UTC Monday through Friday
    - cron: '0 0 * * 2-6'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          source myenv/bin/activate
          python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}