name: Run Python Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script with secret key
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python email_report.py
