name: Run Python Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: sudo docker build -t us_stocks_robot .

      - name: Run Docker container with secrets
        env: API_KEY=${{ secrets.API_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
          PASSWORD=${{ secrets.PASSWORD }}
        run: |
          sudo docker run \
            --env API_KEY="${{ secrets.API_KEY }}" \
            --env SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --env SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
            --env PASSWORD="${{ secrets.PASSWORD }}" \
            us_stocks_robot
