name: Run and Shutdown EC2

on:
  workflow_run:
    workflows: 
      - Deploy to EC2
      - Run Python Code 
    types:
      - completed

jobs:
  shutdown_ec2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Get EC2 instance ID from S3
        run: | 
            aws s3 cp s3://stocks-trading-robot-2024/ec2-instance-id.txt .
            EC2_INSTANCE_ID=$(cat ec2-instance-id.txt)
            echo "EC2_INSTANCE_ID=${EC2_INSTANCE_ID}" >> $GITHUB_ENV

      - name: Shut down EC2 instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ env.EC2_INSTANCE_ID }}