name: Run and Shutdown EC2

on:
  workflow_run:
    workflows: 
      - Deploy to EC2 # workflow name, not file name!
      - Run Python Code 
    types:
      - completed

jobs:
  shutdown_ec2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Shut down EC2 instance
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo shutdown now
